---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load relevant libraries
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(httr)
library(lubridate)
library(caTools)
```

```{r}
token <- read.delim("~/Google Drive File Stream/My Drive/Keys/g_access.txt", stringsAsFactor = FALSE, header = FALSE)
```

```{r}
# Read in current data stored in private github repository
url=paste0("https://raw.githubusercontent.com/OpenDataLiteracy/FinesAndFees/master/Data/DataEntry_MergedDataSet_2019-09-05.csv")
x=GET(url, add_headers(Authorization = paste("token", token, sep = " ")))
finefree <- content(x, type="text/csv", encoding = "UTF-8")
```

```{r}
# help with dates times https://r4ds.had.co.nz/dates-and-times.html
finefree$fine_free_date = as.Date(as_datetime(finefree$fine_free_date))
```

```{r}
finefree %>%
  filter(fine_free_date > "2015-01-01") %>%
  ggplot(aes(x = fine_free_date)) +
  stat_count(geom='col', aes(y=..count..)) +
  scale_x_date(date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1), axis.title.x=element_blank())
```

```{r}
#https://r4ds.had.co.nz/dates-and-times.html
finefree %>%
  filter(fine_free_date > "2010-01-01") %>%
  count(month = floor_date(fine_free_date, "month")) %>% 
  ggplot(aes(month, n)) +
    geom_line()
```

```{r}
# References
# https://r4ds.had.co.nz/dates-and-times.html
# http://www.sthda.com/english/wiki/ggplot2-themes-and-background-colors-the-3-elements
finefree %>%
  filter(fine_free_date > "2010-01-01") %>%
  count(year = floor_date(fine_free_date, "year")) %>% 
  ggplot(aes(year, n)) +
    geom_point(color = "white") +
    geom_line(color = "white") +
    geom_text(aes(label=n), vjust=-0.9, hjust=0.9, size = 4, color = "white") +
    scale_x_date(date_breaks = "1 year",
                 labels=scales::date_format("%Y")) +
    scale_y_continuous(limits = c(0,110)) +
    labs(title="Number of Fine Free Public Libraries in U.S.", y = "Count", x = "Year the Fine-Free Policy was Enacted", size = 4) +
    theme(panel.background = element_rect(fill = "#00ADB2",
                                colour = "#00ADB2",
                                size = 0.5, linetype = "solid"),
          panel.grid.major.y = element_line(size = 0.2, linetype = 'solid',
                                        colour = "white"), 
          panel.grid.major.x = element_blank(),
          panel.grid.minor = element_blank())

ggsave("~/Documents/Github/FinesAndFees/Images/FineFreeLibrariesPerYear.png")
```

```{r}
#https://www.earthdatascience.org/courses/earth-analytics/time-series-data/summarize-time-series-by-month-in-r/
finefree %>%
  mutate(month = month(fine_free_date),
         year = year(fine_free_date)) %>%
  group_by(year) %>%
  count() 
```

```{r}
#https://www.earthdatascience.org/courses/earth-analytics/time-series-data/summarize-time-series-by-month-in-r/
finefree %>%
  mutate(month = month(fine_free_date),
         year = year(fine_free_date)) %>%
  group_by(year, month) %>%
  count() 
```

```{r}
#https://www.earthdatascience.org/courses/earth-analytics/time-series-data/summarize-time-series-by-month-in-r/
finefree %>%
  filter(fine_free_date > "2017-01-01",
         fine_free_date < "2019-02-01",
        !is.na(fine_free_date)) %>%
  mutate(month = month(fine_free_date),
         year = year(fine_free_date)) %>%
  #group_by(year, month) %>%
  count() 
```

```{r}
df <- finefree %>%
  filter(fine_free_date > "2017-01-01",
         fine_free_date < "2019-02-01",
        !is.na(fine_free_date),
        !library_name %in% c("Plano Public Library", "Weymouth Public LIbraries",
                             "Selbyville Public Library", "Kitsap Regional Library",
                             "Racine Public Library", "Lewis Cooper Jr. Memorial Library",
                             "Nashville Public Library", "Santa Clara City Library",
                             "Washington County Cooperative Library Services", "Rochester Public Library"))
split = sample.split(df$library_name, SplitRatio = 0.5)
Bree_set = subset(df, split == TRUE)
Nic_set = subset(df, split == FALSE)

Nic_set <- Nic_set %>%
  select(library_name, state, fine_free_date, type_of_elimination, source)

Bree_set <- Bree_set %>%
  select(library_name, state, fine_free_date, type_of_elimination, source)


write.csv(Bree_set, "~/Documents/GitHub/FinesAndFees/Data/Bree_FOIA.csv")
write.csv(Nic_set, "~/Documents/GitHub/FinesAndFees/Data/Nic_FOIA.csv")
```


```{r}
finefree %>%
  filter(fine_free_date > "2010-01-01",
        !is.na(fine_free_date)) %>%
  #mutate(month = month(fine_free_date),
         #year = year(fine_free_date)) %>%
  #group_by(year, month) %>%
  count() 
```


```{r}
finefree %>%
  filter(fine_free_date > "2017-01-01",
         fine_free_date < "2019-02-01",
        !is.na(fine_free_date)) %>%
 write.csv("~/Documents/GitHub/FinesAndFees/Data/103_FineFree_Libraries.csv")
```


```{r}
finefree %>%
  filter(!is.na(fine_free_date)) %>%
  select(library_name, state, type_of_elimination, fine_free_date, official_policy_link, library_url) %>%
  arrange(desc(fine_free_date)) %>%
  write.csv("~/Documents/GitHub/FinesAndFees/Data/Libraries_with_FineFreeDates.csv")
```

